import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CartState from "@/context";
import { ChakraProvider } from "@chakra-ui/react";
export const metadata = {
  title: "Home",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <CartState>
        <body>
          <ChakraProvider>
            <Navbar />
            {children}
          </ChakraProvider>
        </body>
      </CartState>
    </html>
  );
}
